// src/services/ExerciseService.ts
import { Exercise } from '../types/Index';

const allExercises: Exercise[] = [
    { id: 1, name: 'Liegestütz', category: 'Kraft', description: 'Eine grundlegende Übung zur Stärkung von Brust, Schultern und Trizeps. Start in Plank-Position, Körper absenken, bis die Brust fast den Boden berührt, dann hochdrücken.', reps_duration: '3 Sätze à 8-12 Wiederholungen', normalized_name: 'liegestuetz', image_url: 'https://placehold.co/80x80/000000/FFFFFF?text=Liegestz.jpg' },
    { id: 2, name: 'Kniebeuge', category: 'Kraft', description: 'Effektive Ganzkörperübung, die primär Beine und Po stärkt. Füße schulterbreit, Hüfte nach hinten schieben, als würdest du dich setzen.', reps_duration: '3 Sätze à 10-15 Wiederholungen', normalized_name: 'kniebeuge', image_url: 'https://placehold.co/80x80/000000/FFFFFF?text=Kniebeuge.jpg' },
    { id: 3, name: 'Plank', category: 'Kraft', description: 'Statische Core-Übung, die den gesamten Rumpf stärkt. Halte eine gerade Linie von Kopf bis Fuß, gestützt auf Unterarme und Zehen.', reps_duration: '3 Sätze à 30-60 Sekunden', normalized_name: 'plank', image_url: 'https://placehold.co/80x80/000000/FFFFFF?text=Plank.jpg' },
    { id: 4, name: 'Ausfallschritt', 'category': 'Kraft', 'description': 'Stärkt Beine und Po, verbessert Balance. Ein Bein nach vorne setzen, beide Knie beugen, bis das hintere Knie fast den Boden berührt.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Bein', 'normalized_name': 'ausfallschritt', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Ausfallsch.jpg' },
    { 'id': 5, 'name': 'Kreuzheben', 'category': 'Kraft', 'description': 'Ganzkörperübung für Rücken, Beine und Po. Hebe ein Gewicht vom Boden, indem du Hüfte und Knie streckst, Rücken gerade halten.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'kreuzheben', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Kreuzheben.jpg' },
    { 'id': 6, 'name': 'Rudern mit Kurzhanteln', 'category': 'Kraft', 'description': 'Stärkt den oberen Rücken und Bizeps. Beuge dich nach vorne, Rücken gerade, ziehe Hanteln zum Körper.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'rudernmitkurzhanteln', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Rudern.jpg' },
    { 'id': 7, 'name': 'Schulterdrücken', 'category': 'Kraft', 'description': 'Stärkt Schultern und Trizeps. Hanteln auf Schulterhöhe halten und über Kopf drücken.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'schulterdruecken', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Schulterdr.jpg' },
    { 'id': 8, 'name': 'Bankdrücken (Kurzhanteln)', 'category': 'Kraft', 'description': 'Stärkt Brust, Schultern und Trizeps. Im Liegen Hanteln von der Brust nach oben drücken.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'bankdrueckenkurzhanteln', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Bankdr.jpg' },
    { 'id': 9, 'name': 'Bizeps-Curls', 'category': 'Kraft', 'description': 'Isolationsübung für den Bizeps. Hanteln mit den Handflächen nach oben zum Körper ziehen.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'bizepscurls', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Bizeps.jpg' },
    { 'id': 10, 'name': 'Trizeps-Dips', 'category': 'Kraft', 'description': 'Stärkt den Trizeps. Am Stuhl oder Barren den Körper absenken und wieder hochdrücken.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'trizepsdips', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Trizeps.jpg' },
    { 'id': 11, 'name': 'Glute Bridge', 'category': 'Kraft', 'description': 'Stärkt Gesäß und hintere Oberschenkel. Im Liegen Hüfte anheben, bis Körper eine gerade Linie bildet.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'glutebridge', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=GluteBr.jpg' },
    { 'id': 12, 'name': 'Wadenheben', 'category': 'Kraft', 'description': 'Stärkt die Wadenmuskulatur. Auf den Zehenspitzen auf- und abwippen.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'wadenheben', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Wade.jpg' },
    { 'id': 13, 'name': 'Burpee', 'category': 'HIIT', 'description': 'Ganzkörper-Explosivübung. Kniebeuge, Hände zum Boden, Füße nach hinten springen, Liegestütz, Füße vor, hochspringen.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'burpee', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Burpee.jpg' },
    { 'id': 14, 'name': 'Mountain Climber', 'category': 'HIIT', 'description': 'Kardio- und Core-Übung. In Plank-Position abwechselnd Knie zur Brust ziehen, als würdest du einen Berg hochklettern.', 'reps_duration': '3 Sätze à 30-45 Sekunden', 'normalized_name': 'mountainclimber', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=MtnClimber.jpg' },
    { 'id': 15, 'name': 'Sprintintervalle', 'category': 'HIIT', 'description': 'Verbessert Schnelligkeit und Ausdauer. Kurze, maximale Sprints gefolgt von Gehpausen zur Erholung.', 'reps_duration': '5-8 Intervalle (30 Sek. Sprint, 60 Sek. Gehen)', 'normalized_name': 'sprintintervalle', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Sprint.jpg' },
    { 'id': 16, 'name': 'Box Jumps', 'category': 'HIIT', 'description': 'Explosive Beinübung. Springe mit beiden Füßen auf eine stabile Box oder Erhöhung und lande weich.', 'reps_duration': '3 Sätze à 8-10 Wiederholungen', 'normalized_name': 'boxjumps', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BoxJump.jpg' },
    { 'id': 17, 'name': 'High Knees', 'category': 'HIIT', 'description': 'Intensives Kardio-Training. Auf der Stelle laufen, Knie hoch zur Brust ziehen.', 'reps_duration': '3 Sätze à 30-45 Sekunden', 'normalized_name': 'highknees', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=HighKnees.jpg' },
    { 'id': 18, 'name': 'Jumping Jacks', 'category': 'HIIT', 'description': 'Ganzkörper-Kardio-Übung. Springe, während du Arme und Beine gleichzeitig ausbreitest und wieder zusammenführst.', 'reps_duration': '3 Sätze à 30-60 Sekunden', 'normalized_name': 'jumpingjacks', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=JumpJack.jpg' },
    { 'id': 19, 'name': 'Seilspringen', 'category': 'HIIT', 'description': 'Effektives Kardio-Training. Springe über ein Seil, um Ausdauer und Koordination zu verbessern.', 'reps_duration': '3 Sätze à 60-90 Sekunden', 'normalized_name': 'seilspringen', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Seilsp.jpg' },
    { 'id': 20, 'name': 'Hampelmann', 'category': 'Workout', 'description': 'Ganzkörper-Kardio-Übung. Springe, während du Arme und Beine gleichzeitig ausbreitest und wieder zusammenführst.', 'reps_duration': '3 Sätze à 30-60 Sekunden', 'normalized_name': 'hampelmann', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Hampel.jpg' },
    { 'id': 21, 'name': 'Wandsitzen', 'category': 'Workout', 'description': 'Isometrische Beinübung. Setze dich mit dem Rücken an eine Wand, als würdest du auf einem Stuhl sitzen, Oberschenkel parallel zum Boden.', 'reps_duration': '3 Sätze à 30-60 Sekunden', 'normalized_name': 'wandsitzen', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WandSitz.jpg' },
    { 'id': 22, 'name': 'Rumpfbeugen', 'category': 'Workout', 'description': 'Stärkt die seitlichen Bauchmuskeln. Im Stehen oder Sitzen den Oberkörper seitlich neigen.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen pro Seite', 'normalized_name': 'rumpfbeugen', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Rumpfbg.jpg' },
    { 'id': 23, 'name': 'Beinheben', 'category': 'Workout', 'description': 'Stärkt die unteren Bauchmuskeln. Im Liegen Beine gestreckt heben und senken.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'beinheben', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Beinh.jpg' },
    { 'id': 24, 'name': 'Russian Twist', 'category': 'Workout', 'description': 'Stärkt die schrägen Bauchmuskeln. Im Sitzen Oberkörper leicht zurücklehnen, Füße anheben, Oberkörper seitlich drehen.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen pro Seite', 'normalized_name': 'russiantwist', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=RusTwist.jpg' },
    { 'id': 25, 'name': 'Crunches', 'category': 'Workout', 'description': 'Klassische Bauchübung. Im Liegen Oberkörper anheben, um die Bauchmuskeln zu kontrahieren.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'crunches', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Crunch.jpg' },
    { 'id': 26, 'name': 'Superman', 'category': 'Workout', 'description': 'Stärkt den unteren Rücken und das Gesäß. Im Liegen auf dem Bauch Arme und Beine gleichzeitig anheben.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'superman', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Superman.jpg' },
    { 'id': 27, 'name': 'Vogel-Hund', 'category': 'Workout', 'description': 'Verbessert Balance und Core-Stabilität. Im Vierfüßlerstand abwechselnd gegenüberliegenden Arm und Bein strecken.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Seite', 'normalized_name': 'vogelhund', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=VogelHund.jpg' },
    { 'id': 28, 'name': 'Stehender Oberschenkelvorderseiten-Stretch', 'category': 'Dehnen', 'description': 'Dehnt den Quadrizeps. Im Stehen ein Bein am Fußgelenk fassen und Ferse zum Gesäß ziehen.', 'reps_duration': '30 Sekunden pro Bein', 'normalized_name': 'stehenderoberschenkelvorderseitenstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=OberschV.jpg' },
    { 'id': 29, 'name': 'Liegender Oberschenkelrückseiten-Stretch', 'category': 'Dehnen', 'description': 'Dehnt die Hamstrings. Im Liegen ein Bein gestreckt nach oben halten und mit den Händen zum Körper ziehen.', 'reps_duration': '30 Sekunden pro Bein', 'normalized_name': 'liegenderoberschenkelrueckseitenstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=OberschH.jpg' },
    { 'id': 30, 'name': 'Schulter-/Trizeps-Stretch', 'category': 'Dehnen', 'description': 'Dehnt Schultern und Trizeps. Einen Arm über den Körper ziehen oder hinter dem Kopf beugen.', 'reps_duration': '30 Sekunden pro Seite', 'normalized_name': 'schultertrizepsstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Schulter.jpg' },
    { 'id': 31, 'name': 'Brust-Stretch (Türrahmen)', 'category': 'Dehnen', 'description': 'Dehnt die Brustmuskulatur. Im Türrahmen Arme ausbreiten und nach vorne lehnen.', 'reps_duration': '30 Sekunden', 'normalized_name': 'bruststretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Brust.jpg' },
    { 'id': 32, 'name': 'Hüftbeuger-Stretch (Kniend)', 'category': 'Dehnen', 'description': 'Dehnt die Hüftbeuger. Im Ausfallschritt das hintere Knie auf den Boden legen und Hüfte nach vorne schieben.', 'reps_duration': '30 Sekunden pro Seite', 'normalized_name': 'hueftbeugerstretchkniend', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Hueftbg.jpg' },
    { 'id': 33, 'name': 'Katze-Kuh', 'category': 'Regeneration', 'description': 'Verbessert die Beweglichkeit der Wirbelsäule. Im Vierfüßlerstand abwechselnd Rücken runden und durchhängen.', 'reps_duration': '5-10 Wiederholungen', 'normalized_name': 'katzekuh', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=KatzeKuh.jpg' },
    { 'id': 34, 'name': 'Kindeshaltung', 'category': 'Regeneration', 'description': 'Entspannende Yoga-Haltung. Auf den Fersen sitzen, Oberkörper nach vorne beugen, Stirn auf den Boden legen.', 'reps_duration': '1-2 Minuten halten', 'normalized_name': 'kindeshaltung', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Kindesh.jpg' },
    { 'id': 35, 'name': 'Taube', 'category': 'Regeneration', 'description': 'Dehnt Hüfte und Gesäß. Ein Bein angewinkelt nach vorne legen, das andere gestreckt nach hinten.', 'reps_duration': '1-2 Minuten pro Seite', 'normalized_name': 'taube', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Taube.jpg' },
    { 'id': 36, 'name': 'Faszienrolle (Oberschenkel)', 'category': 'Regeneration', 'description': 'Löst Verspannungen in den Oberschenkeln durch Rollen auf einer Faszienrolle.', 'reps_duration': '1-2 Minuten pro Bein', 'normalized_name': 'faszienrolleoberschenkel', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Faszien.jpg' },
    { 'id': 37, 'name': 'Aktive Erholung (Spaziergang)', 'category': 'Ausdauer', 'description': 'Leichter Spaziergang zur Förderung der Durchblutung und Muskelregeneration.', 'reps_duration': '30-60 Minuten', 'normalized_name': 'aktiveerholungspaziergang', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Spazierg.jpg' },
    { 'id': 38, 'name': 'Fahrradfahren (locker)', 'category': 'Ausdauer', 'description': 'Leichte bis moderate Fahrradfahrt zur Verbesserung der Grundlagenausdauer.', 'reps_duration': '45-60 Minuten', 'normalized_name': 'fahrradfahrenlocker', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Fahrrad.jpg' },
    { 'id': 39, 'name': 'Schwimmen (locker)', 'category': 'Ausdauer', 'description': 'Schonendes Ganzkörpertraining zur Regeneration und Verbesserung der Ausdauer.', 'reps_duration': '30-45 Minuten', 'normalized_name': 'schwimmenlocker', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Schwimmen.jpg' },
    { 'id': 40, 'name': 'Leichter Dauerlauf', 'category': 'Ausdauer', 'description': 'Kontinuierlicher Lauf in moderatem Tempo zur Verbesserung der aeroben Kapazität.', 'reps_duration': '30-60 Minuten', 'normalized_name': 'leichterdauerlauf', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Dauerlauf.jpg' },
    { 'id': 41, 'name': 'Ellipsentrainer', 'category': 'Ausdauer', 'description': 'Gelenkschonendes Kardio-Training, das viele Muskelgruppen beansprucht.', 'reps_duration': '30-45 Minuten', 'normalized_name': 'ellipsentrainer', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Ellipsen.jpg' },
    { 'id': 42, 'name': 'Rudergerät', 'category': 'Ausdauer', 'description': 'Ganzkörper-Kardio-Training, das Kraft und Ausdauer kombiniert.', 'reps_duration': '20-30 Minuten', 'normalized_name': 'rudergeraet', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Ruder.jpg' },
    { 'id': 43, 'name': 'Squat Jumps', 'category': 'HIIT', 'description': 'Explosive Kniebeugen mit Sprung nach oben, um die Schnellkraft zu trainieren.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen', 'normalized_name': 'squatjumps', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=SquatJump.jpg' },
    { 'id': 44, 'name': 'Burpee mit Sprung', 'category': 'HIIT', 'description': 'Variante des Burpees mit einem zusätzlichen Sprung am Ende.', 'reps_duration': '3 Sätze à 8-10 Wiederholungen', 'normalized_name': 'burpeemitsprung', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BurpeeSpr.jpg' },
    { 'id': 45, 'name': 'Leg Raises (Beinheben)', 'category': 'Workout', 'description': 'Effektive Übung für die unteren Bauchmuskeln. Im Liegen Beine gestreckt heben und senken.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'legraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LegRaise.jpg' },
    { 'id': 46, 'name': 'Side Plank', 'category': 'Workout', 'description': 'Stärkt die seitlichen Bauchmuskeln und die Rumpfstabilität. Halte den Körper seitlich auf einem Unterarm gestützt.', 'reps_duration': '3 Sätze à 30-45 Sekunden pro Seite', 'normalized_name': 'sideplank', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=SidePlank.jpg' },
    { 'id': 47, 'name': 'Walking Lunges', 'category': 'Kraft', 'description': 'Dynamische Ausfallschritte, die die Beine und das Gesäß stärken und die Balance verbessern.', 'reps_duration': '3 Sätze à 10-12 Schritte pro Bein', 'normalized_name': 'walkinglunges', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WLunges.jpg' },
    { 'id': 48, 'name': 'Push-up to Plank', 'category': 'Workout', 'description': 'Kombiniert einen Liegestütz mit einer Plank-Position, um Brust, Schultern und Core zu trainieren.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'pushuptoplank', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PushPlank.jpg' },
    { 'id': 49, 'name': 'Bird-Dog', 'category': 'Workout', 'description': 'Verbessert Balance und Core-Stabilität. Im Vierfüßlerstand abwechselnd gegenüberliegenden Arm und Bein strecken.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Seite', 'normalized_name': 'birddog', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BirdDog.jpg' },
    { 'id': 50, 'name': 'Cobra Stretch', 'category': 'Dehnen', 'description': 'Dehnt die Bauchmuskeln und den unteren Rücken. Im Liegen auf dem Bauch den Oberkörper anheben.', 'reps_duration': '30 Sekunden', 'normalized_name': 'cobrastretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Cobra.jpg' },
    { 'id': 51, 'name': 'Butterfly Stretch', 'category': 'Dehnen', 'description': 'Dehnt die inneren Oberschenkel und Hüften. Im Sitzen Fußsohlen zusammenführen und Knie nach außen fallen lassen.', 'reps_duration': '30 Sekunden', 'normalized_name': 'butterflystretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Butterfly.jpg' },
    { 'id': 52, 'name': 'Wall Angel', 'category': 'Regeneration', 'description': 'Verbessert die Beweglichkeit der Schultern und des oberen Rückens. An einer Wand Arme wie bei einem Schneemann bewegen.', 'reps_duration': '10-15 Wiederholungen', 'normalized_name': 'wallangel', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WallAngel.jpg' },
    { 'id': 53, 'name': 'Foam Rolling (Rücken)', 'category': 'Regeneration', 'description': 'Löst Verspannungen im oberen und unteren Rücken durch Rollen auf einer Faszienrolle.', 'reps_duration': '1-2 Minuten', 'normalized_name': 'foamrollingruecken', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FoamRoll.jpg' },
    { 'id': 54, 'name': 'Yoga (Sonnengruß)', 'category': 'Regeneration', 'description': 'Eine Abfolge von Yoga-Posen zur Erwärmung und Verbesserung der Flexibilität.', 'reps_duration': '5-10 Wiederholungen', 'normalized_name': 'yogasonnengruss', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Sonnengr.jpg' },
    { 'id': 55, 'name': 'Power Clean', 'category': 'Kraft', 'description': 'Komplexe Übung für explosive Kraft. Gewicht vom Boden in eine Front-Rack-Position heben.', 'reps_duration': '3 Sätze à 3-5 Wiederholungen', 'normalized_name': 'powerclean', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PowerCl.jpg' },
    { 'id': 56, 'name': 'Box Squat', 'category': 'Kraft', 'description': 'Kniebeuge, bei der man auf eine Box sitzt, um die Tiefe zu kontrollieren und die Explosivität zu verbessern.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'boxsquat', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BoxSquat.jpg' },
    { 'id': 57, 'name': 'Medizinball-Wurf', 'category': 'HIIT', 'description': 'Explosive Ganzkörperübung für Schnellkraft. Medizinball gegen eine Wand werfen oder über Kopf.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'medizinballwurf', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=MedBall.jpg' },
    { 'id': 58, 'name': 'Battle Ropes (Wellen)', 'category': 'HIIT', 'description': 'Intensives Kardio- und Krafttraining mit schweren Seilen.', 'reps_duration': '3 Sätze à 30-45 Sekunden', 'normalized_name': 'battleropeswellen', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BattleR.jpg' },
    { 'id': 59, 'name': 'Farmer\'s Walk', 'category': 'Workout', 'description': 'Ganzkörper-Kraft- und Core-Übung. Gehen mit schweren Gewichten in jeder Hand.', 'reps_duration': '3 Sätze à 30-60 Sekunden', 'normalized_name': 'farmerswalk', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FarmerW.jpg' },
    { 'id': 60, 'name': 'Hanging Leg Raises', 'category': 'Workout', 'description': 'Fortgeschrittene Core-Übung. Im Hängen Beine zur Brust ziehen.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'hanginglegraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=HangLR.jpg' },
    { 'id': 61, 'name': 'Pistol Squat (assistiert)', 'category': 'Kraft', 'description': 'Einbeinige Kniebeuge für Bein- und Gesäßkraft sowie Balance.', 'reps_duration': '3 Sätze à 5-8 Wiederholungen pro Bein', 'normalized_name': 'pistolsquatassistiert', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Pistol.jpg' },
    { 'id': 62, 'name': 'Plyometrische Liegestütze', 'category': 'HIIT', 'description': 'Explosive Liegestütze, bei denen die Hände vom Boden abheben.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'plyometrischeliegestuetze', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PlyoPush.jpg' },
    { 'id': 63, 'name': 'Walking Plank', 'category': 'Workout', 'description': 'Dynamische Plank-Variante, bei der man sich von den Unterarmen auf die Hände und zurück bewegt.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'walkingplank', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WalkPlank.jpg' },
    { 'id': 64, 'name': 'World\'s Greatest Stretch', 'category': 'Dehnen', 'description': 'Dynamischer Ganzkörper-Stretch, der Hüften, Hamstrings und Brust öffnet.', 'reps_duration': '5-8 Wiederholungen pro Seite', 'normalized_name': 'worldsgreateststretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WorldStr.jpg' },
    { 'id': 65, 'name': 'Foam Rolling (Waden)', 'category': 'Regeneration', 'description': 'Löst Verspannungen in den Waden durch Rollen auf einer Faszienrolle.', 'reps_duration': '1-2 Minuten pro Bein', 'normalized_name': 'foamrollingwaden', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FoamWade.jpg' },
    { 'id': 66, 'name': 'Yoga (Krieger II)', 'category': 'Regeneration', 'description': 'Stärkt Beine und Core, dehnt Hüften und Leisten.', 'reps_duration': '30-60 Sekunden pro Seite', 'normalized_name': 'yogakriegerii', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=KriegerII.jpg' },
    { 'id': 67, 'name': 'Barbell Row', 'category': 'Kraft', 'description': 'Grundlegende Rückenübung mit der Langhantel.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'barbellrow', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BarbellR.jpg' },
    { 'id': 68, 'name': 'Overhead Press', 'category': 'Kraft', 'description': 'Stärkt Schultern und Trizeps mit der Langhantel über Kopf.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'overheadpress', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=OHPress.jpg' },
    { 'id': 69, 'name': 'Clean and Jerk (Technik)', 'category': 'Kraft', 'description': 'Olympisches Gewichtheben, Fokus auf Technik für Explosivität.', 'reps_duration': '5 Sätze à 3 Wiederholungen', 'normalized_name': 'cleanandjerktechnik', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=CleanJ.jpg' },
    { 'id': 70, 'name': 'Kettlebell Swing', 'category': 'HIIT', 'description': 'Explosive Ganzkörperübung für Kraft und Ausdauer.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'kettlebellswing', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=KBSwing.jpg' },
    { 'id': 71, 'name': 'Burpee Box Jumps', 'category': 'HIIT', 'description': 'Kombination aus Burpee und Box Jump für maximale Intensität.', 'reps_duration': '3 Sätze à 6-8 Wiederholungen', 'normalized_name': 'burpeeboxjumps', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BBJump.jpg' },
    { 'id': 72, 'name': 'TRX Row', 'category': 'Workout', 'description': 'Rückenübung mit Schlingentrainer, anpassbar an jedes Fitnesslevel.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'trxrow', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=TRXRow.jpg' },
    { 'id': 73, 'name': 'Ball Slams', 'category': 'Workout', 'description': 'Explosive Core-Übung mit einem Medizinball.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'ballslams', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BallSlam.jpg' },
    { 'id': 74, 'name': 'Dynamic Hip Flexor Stretch', 'category': 'Dehnen', 'description': 'Dynamische Dehnung der Hüftbeuger.', 'reps_duration': '10-12 Wiederholungen pro Seite', 'normalized_name': 'dynamichipflexorstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=DynHip.jpg' },
    { 'id': 75, 'name': 'Pigeon Pose (Yoga)', 'category': 'Regeneration', 'description': 'Tiefe Hüftöffnung aus dem Yoga.', 'reps_duration': '1-2 Minuten pro Seite', 'normalized_name': 'pigeonposeyoga', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Pigeon.jpg' },
    { 'id': 76, 'name': 'Foam Rolling (IT Band)', 'category': 'Regeneration', 'description': 'Löst Verspannungen am äußeren Oberschenkel.', 'reps_duration': '1-2 Minuten pro Seite', 'normalized_name': 'foamrollingitband', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=ITBand.jpg' },
    { 'id': 77, 'name': 'Couch Stretch', 'category': 'Dehnen', 'description': 'Intensive Dehnung für Quadrizeps und Hüftbeuger.', 'reps_duration': '1 Minute pro Seite', 'normalized_name': 'couchstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=CouchStr.jpg' },
    { 'id': 78, 'name': 'Thread the Needle (Yoga)', 'category': 'Regeneration', 'description': 'Dehnt Schultern und oberen Rücken.', 'reps_duration': '30-60 Sekunden pro Seite', 'normalized_name': 'threadtheneedleyoga', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=ThreadN.jpg' },
    { 'id': 79, 'name': 'Dead Bug', 'category': 'Workout', 'description': 'Core-Stabilitätsübung im Liegen.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Seite', 'normalized_name': 'deadbug', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=DeadBug.jpg' },
    { 'id': 80, 'name': 'Single Leg RDL', 'category': 'Kraft', 'description': 'Einbeiniges Kreuzheben für Balance und hintere Kette.', 'reps_duration': '3 Sätze à 8-10 Wiederholungen pro Bein', 'normalized_name': 'singlelegrdl', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=SLRDL.jpg' },
    { 'id': 81, 'name': 'Band Pull-Aparts', 'category': 'Kraft', 'description': 'Stärkt die obere Rückenmuskulatur und Schulterblattstabilisatoren mit einem Widerstandsband.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'bandpullaparts', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BandPull.jpg' },
    { 'id': 82, 'name': 'Goblet Squat', 'category': 'Kraft', 'description': 'Kniebeuge mit einer Kurzhantel vor der Brust, gut für die Technik.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'gobletsquat', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=GobletS.jpg' },
    { 'id': 83, 'name': 'Kettlebell Goblet Squat', 'category': 'Kraft', 'description': 'Kniebeuge mit einer Kettlebell vor der Brust, gut für die Technik.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'kettlebellgobletsquat', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=KBGoblet.jpg' },
    { 'id': 84, 'name': 'Renegade Row', 'category': 'Kraft', 'description': 'Kombiniert Plank mit Rudern, trainiert Core und oberen Rücken.', 'reps_duration': '3 Sätze à 8-10 Wiederholungen pro Seite', 'normalized_name': 'renegaderow', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Renegade.jpg' },
    { 'id': 85, 'name': 'Plank Jacks', 'category': 'HIIT', 'description': 'Kardio-Variante der Plank. Füße im Sprung auseinander und zusammen bewegen.', 'reps_duration': '3 Sätze à 30-45 Sekunden', 'normalized_name': 'plankjacks', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PlankJack.jpg' },
    { 'id': 86, 'name': 'Tuck Jumps', 'category': 'HIIT', 'description': 'Explosiver Sprung, bei dem die Knie zur Brust gezogen werden.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'tuckjumps', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=TuckJump.jpg' },
    { 'id': 87, 'name': 'Bear Crawl', 'category': 'Workout', 'description': 'Ganzkörperübung, die Kraft und Koordination trainiert. Krabbeln wie ein Bär.', 'reps_duration': '3 Sätze à 20-30 Sekunden', 'normalized_name': 'bearcrawl', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BearC.jpg' },
    { 'id': 88, 'name': 'Leg Pull-In', 'category': 'Workout', 'description': 'Bauchübung, bei der die Knie zur Brust gezogen werden, sitzend oder hängend.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'legpullin', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LegPull.jpg' },
    { 'id': 89, 'name': 'Spiderman Push-up', 'category': 'Workout', 'description': 'Liegestütz-Variante, bei der ein Knie zum Ellbogen gezogen wird.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'spidermanpushup', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=SpiderP.jpg' },
    { 'id': 90, 'name': 'Triceps Extension (Overhead)', 'category': 'Kraft', 'description': 'Isolationsübung für den Trizeps über Kopf.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'tricepsextensionoverhead', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=TriExt.jpg' },
    { 'id': 91, 'name': 'Face Pulls', 'category': 'Kraft', 'description': 'Stärkt die hintere Schulter und den oberen Rücken, gut für die Haltung.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'facepulls', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FacePull.jpg' },
    { 'id': 92, 'name': 'Good Mornings', 'category': 'Kraft', 'description': 'Stärkt die hintere Kette (Hamstrings, Gesäß, unterer Rücken).', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'goodmornings', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=GoodM.jpg' },
    { 'id': 93, 'name': 'Wall Push-up', 'category': 'Workout', 'description': 'Leichtere Variante des Liegestützes an einer Wand.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'wallpushup', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WallPush.jpg' },
    { 'id': 94, 'name': 'Reverse Crunches', 'category': 'Workout', 'description': 'Bauchübung, bei der die Beine zur Brust gezogen werden.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'reversecrunches', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=RevCrunch.jpg' },
    { 'id': 95, 'name': 'Dynamic Chest Stretch', 'category': 'Dehnen', 'description': 'Dynamische Dehnung für die Brustmuskulatur.', 'reps_duration': '10-15 Wiederholungen', 'normalized_name': 'dynamiccheststretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=DynChest.jpg' },
    { 'id': 96, 'name': 'Leg Swings (Front/Side)', 'category': 'Dehnen', 'description': 'Dynamische Dehnung für Beine und Hüften.', 'reps_duration': '10-15 Wiederholungen pro Seite', 'normalized_name': 'legswingsfrontside', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LegSwing.jpg' },
    { 'id': 97, 'name': 'Cat-Cow Stretch', 'category': 'Regeneration', 'description': 'Verbessert die Beweglichkeit der Wirbelsäule.', 'reps_duration': '5-10 Wiederholungen', 'normalized_name': 'catcowstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=CatCow.jpg' },
    { 'id': 98, 'name': 'Child\'s Pose', 'category': 'Regeneration', 'description': 'Entspannende Yoga-Haltung.', 'reps_duration': '1-2 Minuten halten', 'normalized_name': 'childspose', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=ChildPose.jpg' },
    { 'id': 99, 'name': 'Pigeon Stretch', 'category': 'Regeneration', 'description': 'Tiefe Hüftöffnung.', 'reps_duration': '1-2 Minuten pro Seite', 'normalized_name': 'pigeonstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PigeonStr.jpg' },
    { 'id': 100, 'name': 'Foam Rolling (Quads)', 'category': 'Regeneration', 'description': 'Löst Verspannungen im Quadrizeps.', 'reps_duration': '1-2 Minuten pro Bein', 'normalized_name': 'foamrollingquads', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FoamQuad.jpg' },
    { 'id': 101, 'name': 'Yoga (Downward Dog)', 'category': 'Regeneration', 'description': 'Dehnt den gesamten Körper und stärkt die Arme.', 'reps_duration': '30-60 Sekunden halten', 'normalized_name': 'yogadownwarddog', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=DownDog.jpg' },
    { 'id': 102, 'name': 'Box Step-ups', 'category': 'Kraft', 'description': 'Stärkt Beine und Gesäß, verbessert die einbeinige Kraft.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Bein', 'normalized_name': 'boxstepups', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BoxStep.jpg' },
    { 'id': 103, 'name': 'Dumbbell Rows (Single Arm)', 'category': 'Kraft', 'description': 'Isolierte Rückenübung mit Kurzhantel.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen pro Arm', 'normalized_name': 'dumbbellrowssinglearm', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=DumbRow.jpg' },
    { 'id': 104, 'name': 'Thrusters (Dumbbell)', 'category': 'HIIT', 'description': 'Kombination aus Kniebeuge und Schulterdrücken für Ganzkörper-Explosivität.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'thrustersdumbbell', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Thruster.jpg' },
    { 'id': 105, 'name': 'Kettlebell Swings (Two Hand)', 'category': 'HIIT', 'description': 'Explosive Hüftbewegung für Kraft und Ausdauer.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'kettlebellswingstwohand', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=KBSwing2.jpg' },
    { 'id': 106, 'name': 'Plank with Shoulder Taps', 'category': 'Workout', 'description': 'Stärkt Core und Schultern. In Plank-Position abwechselnd Schultern antippen.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen pro Seite', 'normalized_name': 'plankwithshouldertaps', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PlankTap.jpg' },
    { 'id': 107, 'name': 'Alternating Lunges', 'category': 'Workout', 'description': 'Ausfallschritte, bei denen die Beine abwechselnd nach vorne gesetzt werden.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Bein', 'normalized_name': 'alternatinglunges', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=AltLunge.jpg' },
    { 'id': 108, 'name': 'Standing Quad Stretch', 'category': 'Dehnen', 'description': 'Dehnt den Quadrizeps im Stehen.', 'reps_duration': '30 Sekunden pro Bein', 'normalized_name': 'standingquadstretch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=StandQuad.jpg' },
    { 'id': 109, 'name': 'Hamstring Stretch (Seated)', 'category': 'Dehnen', 'description': 'Dehnt die Hamstrings im Sitzen.', 'reps_duration': '30 Sekunden pro Bein', 'normalized_name': 'hamstringstretchseated', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=HamstrS.jpg' },
    { 'id': 110, 'name': 'Calf Stretch (Wall)', 'category': 'Dehnen', 'description': 'Dehnt die Wadenmuskulatur an einer Wand.', 'reps_duration': '30 Sekunden pro Bein', 'normalized_name': 'calfstretchwall', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=CalfWall.jpg' },
    { 'id': 111, 'name': 'Foam Rolling (Hamstrings)', 'category': 'Regeneration', 'description': 'Löst Verspannungen in den Hamstrings.', 'reps_duration': '1-2 Minuten pro Bein', 'normalized_name': 'foamrollinghamstrings', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FoamHam.jpg' },
    { 'id': 112, 'name': 'Savasana (Corpse Pose)', 'category': 'Regeneration', 'description': 'Entspannende Abschluss-Yoga-Haltung.', 'reps_duration': '5-10 Minuten', 'normalized_name': 'savasanacorpsepose', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Savasana.jpg' },
    { 'id': 113, 'name': 'Wall Sit with Arm Raises', 'category': 'Workout', 'description': 'Kombiniert Wandsitzen mit Armbewegungen für zusätzlichen Schulter- und Core-Einsatz.', 'reps_duration': '3 Sätze à 30-60 Sekunden', 'normalized_name': 'wallsitwitharmraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WallSitAR.jpg' },
    { 'id': 114, 'name': 'Jump Squats', 'category': 'HIIT', 'description': 'Kniebeugen mit einem explosiven Sprung nach oben.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'jumpsquats', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=JumpSquat.jpg' },
    { 'id': 115, 'name': 'Bicycle Crunches', 'category': 'Workout', 'description': 'Dynamische Bauchübung, die schräge und gerade Bauchmuskeln trainiert.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen pro Seite', 'normalized_name': 'bicyclecrunches', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BicycleC.jpg' },
    { 'id': 116, 'name': 'Bird-Dog with Crunch', 'category': 'Workout', 'description': 'Variante des Vogel-Hunds mit einer Knie-Ellbogen-Berührung.', 'reps_duration': '3 Sätze à 10-12 Wiederholungen pro Seite', 'normalized_name': 'birddogwithcrunch', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BirdDogCr.jpg' },
    { 'id': 117, 'name': 'Side Leg Raises', 'category': 'Workout', 'description': 'Stärkt die Hüftabduktoren. Im Liegen auf der Seite Bein heben und senken.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen pro Seite', 'normalized_name': 'sidelegraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=SideLeg.jpg' },
    { 'id': 118, 'name': 'Step-ups', 'category': 'Kraft', 'description': 'Einfache Übung zur Stärkung der Beine und des Gesäßes auf einer Stufe.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen pro Bein', 'normalized_name': 'stepups', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=StepUp.jpg' },
    { 'id': 119, 'name': 'Triceps Push-ups (Diamond)', 'category': 'Kraft', 'description': 'Liegestütz-Variante mit engen Händen, die den Trizeps stärker beansprucht.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'tricepspushupsdiamond', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=TriPush.jpg' },
    { 'id': 120, 'name': 'Walking Planks', 'category': 'Workout', 'description': 'Dynamische Plank-Variante, bei der man sich von den Unterarmen auf die Hände und zurück bewegt.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'walkingplanks', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WalkPlank.jpg' },
    { 'id': 121, 'name': 'Standing Calf Raises', 'category': 'Kraft', 'description': 'Einfache Übung zum Aufbau der Wadenmuskulatur.', 'reps_duration': '3 Sätze à 15-20 Wiederholungen', 'normalized_name': 'standingcalfraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=StandCalf.jpg' },
    { 'id': 122, 'name': 'Leg Press (Machine)', 'category': 'Kraft', 'description': 'Beinübung an der Maschine, gut für den Aufbau der Beinmuskulatur.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'legpressmachine', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LegPress.jpg' },
    { 'id': 123, 'name': 'Lat Pulldown (Machine)', 'category': 'Kraft', 'description': 'Rückenübung an der Maschine, trainiert den breiten Rückenmuskel.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'latpulldownmachine', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LatPull.jpg' },
    { 'id': 124, 'name': 'Overhead Dumbbell Extension', 'category': 'Kraft', 'description': 'Trizeps-Isolationsübung mit einer Kurzhantel über Kopf.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'overheaddumbbellextension', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=OHDumb.jpg' },
    { 'id': 125, 'name': 'Hammer Curls', 'category': 'Kraft', 'description': 'Bizeps-Übung mit neutralem Griff für den Brachialis.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'hammercurls', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=HammerC.jpg' },
    { 'id': 126, 'name': 'Front Squat', 'category': 'Kraft', 'description': 'Kniebeuge mit der Langhantel vor der Brust, fordert Core und Mobilität.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'frontsquat', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FrontSq.jpg' },
    { 'id': 127, 'name': 'Romanian Deadlift (RDL)', 'category': 'Kraft', 'description': 'Variante des Kreuzhebens, die stärker die Hamstrings beansprucht.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'romaniandeadlift', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=RDL.jpg' },
    { 'id': 128, 'name': 'Pull-ups (Assisted)', 'category': 'Kraft', 'description': 'Rückenübung, die den Latissimus und Bizeps stärkt, mit Unterstützung.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'pullupsassisted', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=PullUp.jpg' },
    { 'id': 129, 'name': 'Chin-ups (Assisted)', 'category': 'Kraft', 'description': 'Variante des Klimmzugs mit Untergriff, stärkerer Fokus auf Bizeps.', 'reps_duration': '3 Sätze à 6-10 Wiederholungen', 'normalized_name': 'chinupsassisted', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=ChinUp.jpg' },
    { 'id': 130, 'name': 'Leg Extension (Machine)', 'category': 'Kraft', 'description': 'Isolationsübung für den Quadrizeps.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'legextensionmachine', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LegExt.jpg' },
    { 'id': 131, 'name': 'Leg Curl (Machine)', 'category': 'Kraft', 'description': 'Isolationsübung für die Hamstrings.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'legcurlmachine', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LegCurl.jpg' },
    { 'id': 132, 'name': 'Cable Crossover', 'category': 'Kraft', 'description': 'Brustübung am Kabelzug, gut für die Formgebung.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'cablecrossover', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=CableX.jpg' },
    { 'id': 133, 'name': 'Lateral Raises', 'category': 'Kraft', 'description': 'Isolationsübung für die seitlichen Schultern.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'lateralraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LatRaise.jpg' },
    { 'id': 134, 'name': 'Front Raises', 'category': 'Kraft', 'description': 'Isolationsübung für die vorderen Schultern.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'frontraises', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FrontRaise.jpg' },
    { 'id': 135, 'name': 'Shrugs (Dumbbell)', 'category': 'Kraft', 'description': 'Stärkt den oberen Trapezmuskel.', 'reps_duration': '3 Sätze à 12-15 Wiederholungen', 'normalized_name': 'shrugsdumbbell', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Shrug.jpg' },
    { 'id': 136, 'name': 'Hyperextensions (Back Extension)', 'category': 'Kraft', 'description': 'Stärkt den unteren Rücken und das Gesäß.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen', 'normalized_name': 'hyperextensionsbackextension', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Hyperext.jpg' },
    { 'id': 137, 'name': 'Ab Rollout', 'category': 'Kraft', 'description': 'Fortgeschrittene Core-Übung mit einem Ab-Wheel oder Langhantel.', 'reps_duration': '3 Sätze à 8-12 Wiederholungen', 'normalized_name': 'abrollout', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=AbRoll.jpg' },
    { 'id': 138, 'name': 'Weighted Plank', 'category': 'Kraft', 'description': 'Plank mit zusätzlichem Gewicht auf dem Rücken.', 'reps_duration': '3 Sätze à 30-60 Sekunden', 'normalized_name': 'weightedplank', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=WtdPlank.jpg' },
    { 'id': 139, 'name': 'Sledgehammer Slams', 'category': 'HIIT', 'description': 'Explosive Ganzkörperübung mit einem Vorschlaghammer und Reifen.', 'reps_duration': '3 Sätze à 10-15 Wiederholungen pro Seite', 'normalized_name': 'sledgehammerslams', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Sledge.jpg' },
    { 'id': 140, 'name': 'Tire Flips', 'category': 'HIIT', 'description': 'Ganzkörper-Kraft- und Ausdauerübung mit einem großen Reifen.', 'reps_duration': '3 Sätze à 5-8 Wiederholungen', 'normalized_name': 'tireflips', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=TireFlip.jpg' },
    { 'id': 141, 'name': 'Burpee Pull-ups', 'category': 'HIIT', 'description': 'Kombination aus Burpee und Klimmzug für maximale Intensität.', 'reps_duration': '3 Sätze à 5-8 Wiederholungen', 'normalized_name': 'burpeepullups', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=BurpeePU.jpg' },
    { 'id': 142, 'name': 'Agility Ladder Drills', 'category': 'HIIT', 'description': 'Übungen mit der Koordinationsleiter zur Verbesserung von Schnelligkeit und Agilität.', 'reps_duration': '5-10 Minuten', 'normalized_name': 'agilityladderdrills', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=AgilityL.jpg' },
    { 'id': 143, 'name': 'Box Drills (Cone Drills)', 'category': 'HIIT', 'description': 'Schnelle Richtungswechsel um Hütchen zur Verbesserung der Agilität.', 'reps_duration': '5-10 Minuten', 'normalized_name': 'boxdrillsconedrills', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=ConeDrill.jpg' },
    { 'id': 144, 'name': 'Jump Rope Intervals', 'category': 'Ausdauer', 'description': 'Intensives Seilspringen mit kurzen Pausen.', 'reps_duration': '3-5 Intervalle (2 Min. Springen, 1 Min. Pause)', 'normalized_name': 'jumpropeintervals', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=JumpRope.jpg' },
    { 'id': 145, 'name': 'Rowing Machine Intervals', 'category': 'Ausdauer', 'description': 'Intensives Rudern auf dem Rudergerät mit kurzen Pausen.', 'reps_duration': '3-5 Intervalle (2 Min. Rudern, 1 Min. Pause)', 'normalized_name': 'rowingmachineintervals', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=RowInt.jpg' },
    { 'id': 146, 'name': 'Stair Climber', 'category': 'Ausdauer', 'description': 'Simuliert Treppensteigen, sehr effektiv für Beine und Ausdauer.', 'reps_duration': '30-45 Minuten', 'normalized_name': 'stairclimber', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=StairCl.jpg' },
    { 'id': 147, 'name': 'Elliptical Intervals', 'category': 'Ausdauer', 'description': 'Intervalltraining auf dem Ellipsentrainer.', 'reps_duration': '3-5 Intervalle (3 Min. Intensiv, 2 Min. Moderat)', 'normalized_name': 'ellipticalintervals', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=ElliptInt.jpg' },
    { 'id': 148, 'name': 'Long Distance Run', 'category': 'Ausdauer', 'description': 'Längerer Lauf in moderatem Tempo zur Verbesserung der aeroben Ausdauer.', 'reps_duration': '60-90 Minuten', 'normalized_name': 'longdistancerun', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=LongRun.jpg' },
    { 'id': 149, 'name': 'Foam Rolling (Glutes)', 'category': 'Regeneration', 'description': 'Löst Verspannungen im Gesäßbereich.', 'reps_duration': '1-2 Minuten pro Seite', 'normalized_name': 'foamrollingglutes', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=FoamGlute.jpg' },
    { 'id': 150, 'name': 'Dynamic Warm-up (Full Body)', 'category': 'Regeneration', 'description': 'Aufwärmübung mit dynamischen Bewegungen für den gesamten Körper.', 'reps_duration': '10-15 Minuten', 'normalized_name': 'dynamicwarmupfullbody', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=DynWarm.jpg' },
    { 'id': 151, 'name': 'Cool-down Stretch (Full Body)', 'category': 'Dehnen', 'description': 'Abschließende Dehnübungen für den gesamten Körper nach dem Training.', 'reps_duration': '10-15 Minuten', 'normalized_name': 'cooldownstretchfullbody', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=CoolDwn.jpg' },
    { 'id': 152, 'name': 'Yoga Flow (Gentle)', 'category': 'Regeneration', 'description': 'Sanfter Yoga-Flow zur Entspannung und Verbesserung der Flexibilität.', 'reps_duration': '30-45 Minuten', 'normalized_name': 'yogaflowgentle', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=YogaFlow.jpg' },
    { 'id': 153, 'name': 'Mindful Breathing', 'category': 'Regeneration', 'description': 'Atemübungen zur Entspannung und Stressreduktion.', 'reps_duration': '5-10 Minuten', 'normalized_name': 'mindfulbreathing', 'image_url': 'https://placehold.co/80x80/000000/FFFFFF?text=Breath.jpg' }
];

export const fetchExercisesFromDb = async (workoutType: string): Promise<Exercise[]> => {
    await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate API call delay

    let filteredExercises: Exercise[] = [];
    const getRandomExercises = (categoryList: Exercise[], count: number): Exercise[] => {
        const shuffled = [...categoryList].sort(() => 0.5 - Math.random());
        return shuffled.slice(0, count);
    };

    switch (workoutType) {
        case 'Arbeits-Workout':
            const workoutCategory = allExercises.filter(ex => ex.category === 'Workout');
            filteredExercises = getRandomExercises(workoutCategory, 4);
            break;
        case 'Krafttraining':
            const kraftCategory = allExercises.filter(ex => ex.category === 'Kraft');
            filteredExercises = getRandomExercises(kraftCategory, 5);
            break;
        case 'HIIT/Schnellkraft':
            const hiitCategory = allExercises.filter(ex => ex.category === 'HIIT');
            filteredExercises = getRandomExercises(hiitCategory, 4);
            break;
        case 'Regeneration/Dehnen':
            const regenDehnenCategory = allExercises.filter(ex => ex.category === 'Regeneration' || ex.category === 'Dehnen');
            filteredExercises = getRandomExercises(regenDehnenCategory, 6);
            break;
        default:
            filteredExercises = [];
    }
    return filteredExercises;
};
